### ISSUE TITLE
New version may be needed for 2020 ... advice please

### ISSUE THREAD

**Issue by GrahamTheHat** [Acumatica/Acumatica-ConfigurableTimeSpan#1]
Hi Dhiren,

I'm a newb to GitHub and C# - old time machine code programmer, COBOL, Pascal etc so multiple things to ask forgiveness for.

I have a need for this extension for a client but when trying to use it on 2020 R2 it fails. 

When I try to access form EP305000 I get the error shown in the attached screen shot. Expanding the trace (also attached as a screen shot) doesn't help me I'm afraid as it is beyond my current capabilities.

The package validated and installed without error, and accessing the Time and Expenses Preferences screen gave me exactly what I expected - a new entry box for the time lookup interval. I entered 15 into this, went to add a new time card and got the issue illustrated. Unpublishing the package fixed the issue (as would be expected)

Could you advise on how best to get this working please ? I'm afraid I don't know how best to go about this, and I'm unsure of the protocol on GitHub for reporting this kind of thing so any advice would be most welcomed.

My many thanks,
Graham Martin

![ConfigurableTimeSpan_issue_1](https://user-images.githubusercontent.com/49095350/100763748-7f3e7f00-33ed-11eb-8c1a-004934e27952.png)
![ConfigurableTimeSpan_issue_2](https://user-images.githubusercontent.com/49095350/100763750-7fd71580-33ed-11eb-82b8-fd492fc09c9b.png)

**Comment by DhirenChhapgar** [comment]
Hi Graham,

You can download updated package which is compatible with 2020R1 and 2020R2.

Regards,
Dhiren

**Comment by GrahamTheHat** [comment]
Thank you very much Dhiren - have a great day, you just made mine better 🥇
